version: '3.8'

services:
  todo-nuxt:
    container_name: todo-nuxt
    build:
      context: ./TodoNuxt
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BASE_API_URL=http://localhost:5108/api/
    depends_on:
      - todo-dotnet

  todo-dotnet:
    container_name: todo-dotnet
    build:
      context: .
      dockerfile: TodoApplication/Dockerfile
    ports:
      - "5108:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
